import Head from 'next/head';
// Custom Components
import Navbar from '../components/Navbar';

export default function Main() {
  return (
    <div>
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/task_management_icon.png" />
      </Head>

      <Navbar />
    </div>
  );
}
